# Dockerfile Client
FROM node:18-alpine3.15

WORKDIR /app

RUN apk add --no-cache protobuf

ENV protoc_gen_grpc_web=./node_modules/.bin/protoc-gen-grpc-web

COPY ./client/package.json .
COPY ./client/yarn.lock .
COPY ./protos/greeting.proto .

RUN yarn install

RUN mkdir -p ./src/protos
RUN protoc -I=. ./greeting.proto \
    --plugin=protoc-gen-grpc-web=./node_modules/.bin/protoc-gen-grpc-web \
    --js_out=import_style=commonjs:./src \
    --grpc-web_out=import_style=commonjs,mode=grpcwebtext:./src

COPY ./client .

EXPOSE 8081
CMD ["yarn", "start"]