FROM    node:16.14.2-alpine3.15

WORKDIR /app

COPY    ./server/package.json .
COPY    ./server/yarn.lock .

RUN     yarn install

COPY    ./protos/greeting.proto .
COPY    ./server/server.js .

ENTRYPOINT ["node", "server.js"]