services:
  client_service:
    build:
      context: .
      dockerfile: Dockerfile-client
    ports:
      - "3000:3000"
    stop_signal: SIGINT
    depends_on:
      - envoy_service
      - server_service

  server_service:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "50051:50051"

  envoy_service:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    ports:
      - "8000:8000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml