FROM    alpine:3.15.1

WORKDIR /app

RUN     apk add --no-cache protoc

COPY    ./protos/api.proto .

# build proto descriptor
RUN     protoc --include_imports --include_source_info \
            --descriptor_set_out=api.pb api.proto

FROM    envoyproxy/envoy:v1.22.0

