FROM    alpine:3.15.1

WORKDIR /app

COPY    ./protos/greeting.proto .

# build proto descriptor
RUN     protoc --include_imports --include_source_info \
            --descriptor_set_out=greeting.pb greeting.proto

FROM    envoyproxy/envoy:v1.22.0

